config/routes.rb
Rails.application.routes.draw do
  root 'emails#index'
  resources :emails, only: [:index, :show]
  resources :tracker_patterns, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :whitelisted_tracking_senders,
            only: [:create, :destroy],
            param: :email,
            constraints: { email: /.+(@|(%40)).+\..*/ }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/email.rb
class Email < ApplicationRecord
  def from_whitelisted_tracking_sender?
    @from_whitelisted_tracking_sender ||=
      WhitelistedTrackingSender.all.pluck(:email).include?(from)
  end

  def tracker_count
    @tracker_count ||= begin
      body
      @tracker_count
    end
  end

  def body
    @body ||= begin
      @tracker_count = 0
      TrackerPattern.pluck(:pattern).each do |known_tracker|
        tracker_pattern = "//img[contains(@src, \"#{known_tracker}\")]"
        body_as_html.xpath(tracker_pattern).each do |tracker_tag|
          bounce_tracker(tracker_tag) unless from_whitelisted_tracking_sender?
          @tracker_count += 1
        end
      end
      body_as_html.serialize(save_with: 0)
    end
  end

  def body_as_html
    @body_as_html ||= Nokogiri::HTML(raw_body) do |config|
      config.options = Nokogiri::XML::ParseOptions::NOBLANKS
    end
  end

  def bounce_tracker(tracker_tag)
    tracker_tag['data-src'] = tracker_tag['src']
    tracker_tag['data-target'] = 'bouncer.tracker'
    tracker_tag.remove_attribute('src')
    tracker_tag.add_class('blocked-tracker')
  end
end

app/models/tracker_pattern.rb
class TrackerPattern < ApplicationRecord
end

app/models/whitelisted_tracking_sender.rb
class WhitelistedTrackingSender < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController
  def index
    @emails = Email.all.order(received_at: :desc)
  end

  def show
    @email = Email.find(params[:id])
  end
end

app/controllers/tracker_patterns_controller.rb
class TrackerPatternsController < ApplicationController
  def index
    @tracker_patterns = TrackerPattern.all
  end

  def show
    @tracker_pattern = TrackerPattern.find(params[:id])
  end

  def new
    @tracker_pattern = TrackerPattern.new
  end

  def create
    @tracker_pattern = TrackerPattern.new(create_params)

    if @tracker_pattern.save
      redirect_to tracker_patterns_path
    else
      flash.now[:error] = 'Could not create tracker pattern'
      render action: 'new'
    end
  end

  def edit
    @tracker_pattern = TrackerPattern.find(params[:id])
  end

  def update
    @tracker_pattern = TrackerPattern.find(params[:id])
    if @tracker_pattern.update(update_params)
      redirect_to tracker_patterns_path
    else
      flash.now[:error] = 'Could not update tracker pattern'
      render action: 'edit'
    end
  end

  def destroy
    @tracker_pattern = TrackerPattern.find(params[:id])
    @tracker_pattern.destroy
    redirect_to tracker_patterns_path
  end

  private

  def create_params
    params.require(:tracker_pattern).permit(:name, :pattern)
  end

  def update_params
    create_params
  end
end

app/controllers/whitelisted_tracking_senders_controller.rb
class WhitelistedTrackingSendersController < ApplicationController
  def create
    WhitelistedTrackingSender.create(create_params)
  end

  def destroy
    WhitelistedTrackingSender.find_by(email: params[:email]).destroy
  end

  private

  def create_params
    params.permit(:email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/tracker_patterns_helper.rb
module TrackerPatternsHelper
end

app/helpers/whitelisted_tracking_senders_helper.rb
module WhitelistedTrackingSendersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImageBouncer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="repo-link">
      <%= link_to "https://gitlab.com/image-bouncing/bouncer", target: '_blank' do %>
        <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/GitLab_Logo.svg/1200px-GitLab_Logo.svg.png" alt="Gitlab logo" />
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/tracker_notifications/_allowed_tracker_notification.html.erb
<div class="tracker-notification tracker-notification--whitelisted" data-target='bouncer.trackerNotification'>
  <p>The sender of this email included <%= pluralize(count, 'tracker') %> to gather information from you when you open this email.</p>
  <p>You've told us to allow trackers from this sender, so we're letting them come through.</p>
  <button data-action="bouncer#rebounce" class="button">Block trackers for <%= from %></button>
</div>

app/views/tracker_notifications/_bounced_tracker_notification.html.erb
<div class="tracker-notification" data-target='bouncer.trackerNotification'>
  <h2>We caught 'em!</h2>
  <p>The sender of this email included <%= pluralize(count, 'tracker') %> to gather information from you when you open this email.</p>
  <p>To protect your privacy, we've blocked this tracker automatically.</p>
  <button data-action="bouncer#loadOnce" class="button">Load trackers just this time</button>
  <button data-action="bouncer#override" class="button">Allow trackers for <%= from %></button>
</div>

app/views/tracker_notifications/_tracker_notification.html.erb
<% if email.tracker_count > 0 %>
  <% locals = { from: email.from, count: email.tracker_count } %>
  <% if email.from_whitelisted_tracking_sender? %>
    <%= render partial: '/tracker_notifications/allowed_tracker_notification',
               locals: locals %>
  <% else %>
    <%= render partial: '/tracker_notifications/bounced_tracker_notification',
               locals: locals %>
  <% end %>
<% end %>

app/views/tracker_patterns/_form.html.erb
<%= form_with(model: tracker_pattern, method: (action == 'create' ? 'post' : 'put')) do |f| %>
  <div class="field-group">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field-group">
    <%= f.label :pattern %><br />
    <%= f.text_field :pattern %>
  </div>
  <%= f.submit action.capitalize %>
<% end %>

app/views/tracker_patterns/_tracker_pattern.html.erb
<li class="tracker-pattern">
  <span class="tracker-pattern__name"><%= tracker_pattern.name %></span>
  (<span class="tracker-pattern__pattern"><%= tracker_pattern.pattern %></span>)
  <%= link_to 'Edit', edit_tracker_pattern_path(tracker_pattern), class: 'button button--small' %>
  <%= link_to 'Delete', tracker_pattern_path(tracker_pattern), class: 'button button--small', method: :delete %>
</li>

app/views/tracker_patterns/edit.html.erb
<p><%= link_to 'Back', tracker_patterns_path, class: 'button' %></p>
<h1>Update Tracker Pattern</h1>

<%= render partial: 'form',
           locals: { tracker_pattern: @tracker_pattern, action: 'update' } %>

app/views/tracker_patterns/index.html.erb
<p><%= link_to 'Back', root_path, class: 'button' %></p>
<h1>Known Tracker Patterns</h1>

<ul class="tracker-pattern-list">
  <%= render partial: 'tracker_pattern', collection: @tracker_patterns %>
  <li><%= link_to 'Add new pattern', new_tracker_pattern_path %></li>
</ul>

app/views/tracker_patterns/new.html.erb
<p><%= link_to 'Back', tracker_patterns_path, class: 'button' %></p>
<h1>Create Tracker Pattern</h1>

<%= render partial: 'form',
           locals: { tracker_pattern: @tracker_pattern, action: 'create' } %>